### ISSUE TITLE
Alternate storage location

### ISSUE THREAD

**Issue by davmaz** [jmcfarlane/notable#64]
Great application! But how can the notable storage be located on a Google Drive rather than .notable ?

**Comment by jmcfarlane** [comment]
The database ([BoltDB](https://github.com/boltdb/bolt)) and full text index ([Bleve](https://github.com/blevesearch/bleve)) require filesystem access. Are you looking for a feature that would automatically backup these files to a cloud provider of some kind (S3, Google drive, Azure whatever, etc)?

**Comment by davmaz** [comment]
I would like to have all of the storage for notable exist on a Google Drive. I made a directory (.notable) on my Google Drive, then I made a symbolic link to it from my home directory. However, when I change notable entries, it doesn't sync them properly (because it's a hidden file?).

I could make a hard link.

**Comment by davmaz** [comment]
Hi John,
  Yes, I would like to be able to back up the information to a Google Drive (then I can access it from any device). Maybe this is too complicated to ask, no? I was under the impression that all 'notable' data was stored in the .notable directory. Not true, eh?

Best,
Dave
________________________________________

**Comment by jmcfarlane** [comment]
Hey Dave,

Notable persists data to a single directory. By default the storage looks like this:

```
$ tree ~/.notable
/home/jmcfarlane/.notable
├── notes.db
└── notes.db.idx
    ├── index_meta.json
    └── store
```

I happen to store the data on a different folder that automatically gets backed up. I don't include the index data because it's ephemeral (can be recreated at any time). Here's what I currently use:

```
$ tree ~/.notable
/home/jmcfarlane/.notable
├── notes.db -> /home/jmcfarlane/Sync/Notes/notes.db
└── notes.db.idx
    ├── index_meta.json
    └── store
```

A test setup can be observed by running the following commands:

```
$ mkdir /tmp/dave
$ notable -port 8081 -daemon=false -db=/tmp/dave/notes.db
```

Results in data like this:

```
$ tree /tmp/dave
/tmp/dave
├── notes.db
└── notes.db.idx
    ├── index_meta.json
    └── store
```

I don't happen to have any experience with mounting google drive, but what you described should work just fine (I've ran mine that way since the very beginning). For what it's worth I just pushed up `0.0.10` as a pre-release version. It includes a few fixes to the boot process, and might bubble up errors previously hidden.

https://github.com/jmcfarlane/notable/releases/tag/v0.0.10

**Comment by davmaz** [comment]
Hello John,
  Thanks for the fantastic post. It seems to be working the way you described. I didn't know about the -db option.
  Is it too much to ask if there's a way to have the actual note window use a larger font? If it were the same size as the other sections of the window that would be fine.

  Thanks again for the great app. I'm addicted!

Yours,
Dave
________________________________________

**Comment by davmaz** [comment]
Hi John,
  I thought you had nailed the problem for me in your previous Email, but it isn't working. Here's my situation: I have 2 machines that can connect to my google drive. On one, I execute: 
notable -port 8888 -db=/opt/Google/notes.db  
on the other machine I execute: 
notable -port 8888 -db=/home/dmazzoni/Projects/Drive/notes.db
which shows the Google Drive has a different mount point on each machine.

However, a change on one does not show up on the other. I see the notes.db and the notes.db.idx directory from both, but I don't see changes in the web files/interface. The Google drive syncs automatically whenever I change it, but no joy with notable.

Any ideas?

Best,
Dave 

________________________________________

**Comment by jmcfarlane** [comment]
That sounds about right. Notable supports backup/replication via simple file copy (say using `awscli` or whatever), but it is not a distributed datastore - meaning there (currently) cannot be multiple readers/writers.

It so happens I had a crazy idea that might just make this situation plausible. I'll see if I can code it up on a topic branch for testing :)

**Comment by jmcfarlane** [comment]
@davmaz if you wanna give this a test, an experimental release can be found here:

https://github.com/jmcfarlane/notable/releases/tag/v0.1.0

The raw steps would be to do:

1. Run notable per usual on a machine that has some sort of file sharing enabled. Being sure to write the database to that shared location, via the `-db` option.
2. Run notable with `-db` pointing to the same shared location on another computer, and **also** add the `-secondary` flag.

^ will setup a primary and secondary, where both are available for writes (and changes sync up <=4 seconds + the sync time of whatever service you're using. If you happen to give this a shot I'd low to know how it goes (and on which platform you try it :)

**Comment by jmcfarlane** [comment]
Closing as fixed.
