### ISSUE TITLE
How to compile notable for arm?

### ISSUE THREAD

**Issue by helloray** [jmcfarlane/notable#95]
I compiled it by "env GOOS=linux GOARCH=arm GOARM=5 make".
When I run it, it crashed with below output.

panic: could not locate box "static"

goroutine 1 [running]:
github.com/jmcfarlane/notable/vendor/github.com/GeertJohan/go%2erice.MustFindBox(0x40f6a2, 0x6, 0x664ca861)

**Comment by GarrisonBaird** [comment]
It would be great if @jmcfarlane provides an arm binary in the release

**Comment by GarrisonBaird** [comment]
I successfully compiled v0.1.2 arm builds. **[Binaries here](https://www.dropbox.com/sh/fn8huxiyed93st3/AADYtKSwszybelvqD66eYu59a?dl=0)**
1. Get latest go from https://golang.org/dl/
2. Install decencies in [binary-deps.sh](/jmcfarlane/notable/blob/11ab99d96d87fa77973b1321ba16d485e535ba1b/scripts/binary-deps.sh)
2. Install other decencies by running `go get github.com/jmcfarlane/notable`
3. Compile by running following commands:
```sh
TAG="v0.1.2"
goos="linux"
arch="armv7"

buildArch="-X main.buildArch"
export GOARCH="arm"
export GOARM="7"

mkdir -p target/notable-${TAG}.${goos}-${arch}
cp LICENSE target/notable-${TAG}.${goos}-${arch}

export GOOS=$goos
export CGO_ENABLED=0
go build -o target/notable-${TAG}.${goos}-${arch}/notable
```
Change `arch` and `GOARM` as you need, for a modern Raspberry Pi is armv7
